### ISSUE TITLE
Add Jedpay (JED)

### ISSUE THREAD

**Issue by Jedpay** [forkdelta/tokenbase#1582]
```yaml
---
addr: '0xfae08bde704a3bd3590f88dcb1a5d226a3c63097'
decimals: 18
description: >-
  Global Aggregated Payment System for Cryptocurrency
  Your simple, integrated payment method
links:
- Facebook: https://www.facebook.com/jedpay.io/
- Github: https://github.com/Jedpay
- Medium: https://medium.com/@jedpay.info1
- Telegram: https://t.me/JedpayOfficial
- Twitter: https://twitter.com/jedpay
- Website: https://www.jedpay.io/
- Whitepaper: https://www.jedpay.io/download/whitepaper_en.pdf
- YouTube: https://www.youtube.com/channel/UCCZoUFE18hsxiWTxpow55Ag
name: Jedpay
symbol: JED
```

**Token address:**
0xfae08bde704a3bd3590f88dcb1a5d226a3c63097

**Issuer's official website:**
https://www.jedpay.io/

**Description:**
Jedpay is a blockchain-based aggregated payment system for cryptocurrency and a financial
instrument helping users to exchange, pay and transfer currencies across the world in an
efficient and low-cost manner. It consists of three major functions: wallet, exchange and
payment.
JED token is mostly an incentive for consumers and merchants to pay using Jedcash (which is a stable coin tethered to Thai Baht). It can be earned through "spending is mining" and can be used to pay for exchange fees and merchant service fees at a discounted rate. 

**A link to the official contract address confirmation:** 
Our token contract address can found in our website's footer (https://www.jedpay.io/)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. http://www.keyc.com/story/38675738/blockchain-tourism-jedpay-made-its-debut-at-the-tokensky-summit-in-tokyo-2018
2. https://www.sohu.com/a/246372526_100233312/?pvid=000115_3w_a
